apiVersion: apps/v1
kind: Deployment
metadata:
  name: aps-cloud-ui
  namespace: hwaps-test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: aps-cloud-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aps-cloud-ui
    spec:
      containers:
        - env:
            - name: envir
              valueFrom:
                configMapKeyRef:
                  key: envir
                  name: aps-config
            - name: nacos
              valueFrom:
                configMapKeyRef:
                  key: nacos
                  name: aps-config
            - name: namespace
              valueFrom:
                configMapKeyRef:
                  key: namespace
                  name: aps-config
          image: ${IMAGE}
          imagePullPolicy: IfNotPresent
          name: aps-sit
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: volume-1652146691990
              subPath: nginx.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      imagePullSecrets:
        - name: kb
