kind: Service # 指定创建资源的角色/类型
apiVersion: v1 # 指定api版本，此值必须在kubectl api-versions中
metadata: # 资源的元数据/属性
  name: aps-cloud-ui # 资源的名字，在同一个namespace中必须唯一
  namespace: 	aps-service # 部署在哪个namespace中
spec:
  selector: # 选择器
    app: aps-cloud-ui
  type: NodePort # NodePort 类型
  ports:
    - name: http # 端口名称
      nodePort: 30802 # 主机端口
      port: 80 # 服务端口
      targetPort: 80 # 容器暴露的端口
      protocol: TCP # 协议
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aps-cloud-ui # 资源的名字，在同一个namespace中必须唯一
  namespace: 	aps-service # 部署在哪个namespace中
  labels:
    app: aps-cloud-ui
spec:
  replicas: 1 # 声明副本数目
  revisionHistoryLimit: 1 # 保留历史版本
  selector:
    matchLabels:
      app: aps-cloud-ui
  template:
    metadata:
      labels:
        app: aps-cloud-ui
    spec:
      imagePullSecrets: # 镜像仓库拉取密钥
      - name: pipeline-docker-registry
      containers:
      - name: aps-cloud-ui # 容器的名字
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE} # 容器使用的镜像地址
        ports:
          - name: http # 名称
            containerPort: 30802 # 容器开发对外的端口
            protocol: TCP # 协议
