apiVersion: apps/v1
kind: Deployment
metadata:
  name: aps-cloud-ui
  namespace: hwaps-uat
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: aps-cloud-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        redeploy-timestamp: '1652696296963'
      labels:
        app: aps-cloud-ui
    spec:
      containers:
        - image: ${IMAGE}
          imagePullPolicy: IfNotPresent
          name: aps-cloud-ui
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: volume-1652672555319
              subPath: nginx.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      imagePullSecrets:
        - name: kb
