/** 快码 */
export class MenuManagerInputDto {
    /** 菜单ID */
    public menuId: string;
    /** 菜单編碼 */
    public menuCode: string;
    /** 菜单名称 */
    public menuName: string;
    /** 菜单类型 */
    public menuType: string;
    /** 父菜单ID */
    public parentMenuId: string;
    /** 语言代码 */
    public language: string;
    /** 菜单顺序 */
    public menuSequence: number;
    /** 功能ID */
    public functionId: string;
    /** 编码描述 */
    public description: string;
    /** 生效日期 */
    public startDate: Date;
    /** 失效日期 */
    public endDate: Date;
    /** 窗口类型 */
    public windowType: string;
    /** 系统参数 */
    public parameters: string;
    /** 应用模块ID */
    public applicationId: string;
    /** 图片 */
    public attribute1: string;
    /** TCode */
    public attribute2: string;
}
