/** 快码 */
export class MessageInputDto {
    /** 消息ID */
    public MESSAGEID: string;
    /** 消息代码 */
    public MESSAGECODE: string;
    /** 消息 */
    public MESSAGETEXT: string;
    /** 创建日期 */
    public CREATIONDATE: string;
    /** 创建人 */
    public CREATEDBY: string;
    /** 修改日期 */
    public LASTUPDATEDATE: string;
    /** 修改人 */
    public LASTUPDATEDBY: string;
    /** 应用模块ID */
    public APPLICATIONID: string;
    /** 应用简称 */
    public APPLICATIONSHORTNAME: string;
    /** 应用名称 */
    public APPLICATIONNAME: string;
    /** 编码描述 */
    public DESCRIPTION: string;
    /** 语言代码 */
    public LANGUAGE: string;
    /** 语言 */
    public LNG: string;
}
