/** 用户管理信息Db字段（中间件返回信息） */
export class UserManagerInputDtoDb {
    /** 用户名 */
    public USER_NAME: string;
    /** 描述 */
    public DESCRIPTION: string;
    /** 生效时间从 */
    public StartBegin: string;
    /** 生效时间止   */
    public StartEnd: string;
    /** 失效时间从 */
    public EndBegin: string;
    /** 失效时间止 */
    public EndEnd: string;
    /** 新增修改标记 */
    public p: string;
    /** 密码 */
    public USER_PASSWORD: string;
    /** 生效时间 */
    public START_DATE: string;
    /** 失效时间 */
    public END_DATE: string;
    /** 部门 */
    public DEPARTMENT: string;
    /** 邮件地址 */
    public EMAIL_ADDRESS: string;
    /** 手机号码 */
    public PHONE_NUMBER: string;
    /** 用户ID */
    public USER_ID: string;
    /** 菜单ID */
    public MENU_ID: string;
    /** 职责Id */
    public RESP_ID: string;
    /** 用户职责ID */
    public USER_RESP_ID: string;
}
