/** 用户管理信息 */
export class UserManagerInputDto {
    /** 用户名 */
    public UserName: string;
    /** 描述 */
    public Description: string;
    /** 生效时间从 */
    public StartBegin: string;
    /** 生效时间止   */
    public StartEnd: string;
    /** 失效时间从 */
    public EndBegin: string;
    /** 失效时间止 */
    public EndEnd: string;
    /** 新增修改标记 */
    public p: string;
    /** 密码 */
    public PassWord: string;
    /** 生效时间 */
    public StatDateTime: string;
    /** 失效时间 */
    public EndDataTime: string;
    /** 部门 */
    public DEPARTMENT: string;
    /** 邮件地址 */
    public EMAIL_ADDRESS: string;
    /** 手机号码 */
    public PHONE_NUMBER: string;
    /** 用户ID */
    public UserID: string;
    /** 菜单ID */
    public MenuId: string;
    /** 职责Id */
    public Resp_id: string;
    /** 用户职责ID */
    public User_Resp_id: string;
}
